### ISSUE TITLE
OC City Trends

### ISSUE THREAD

**Issue by vnminin** [damonbayer/uci_covid19_dashboard#11]
Community leaders in OC are asking about trends in areas within OC. E.g., UCI Public Health frequently gets questions like "How is Santa Ana doing?" 

Daniel Parker and I propose to use OCHCA data to plot city trends of cases, deaths, testing, and positivity percents. 

We could start with the top 5 most populous cities: Anaheim, Santa, Ana, Irvine, Huntington Beach, and Garden Grove

I am going to add to the repo a table of OC zip codes and their corresponding cities that Daniel had provided.

**Comment by damonbayer** [comment]
addressed in 5aa40d5fffd2c4fca352b952f25c602a830472ee
