### ISSUE TITLE
More OC cities

### ISSUE THREAD

**Issue by vnminin** [damonbayer/uci_covid19_dashboard#15]
It would be great to add more sets of OC cities, with a dropdown menu. Should be similar to how we have multiples sets of CA counties. 

Here is my proposal for additional sets:

Northern OC: Santa Ana, Anaheim, Garden Grove, Fullerton, Orange
Southern OC: Irvine, Costa Mesa, Mission Viejo, Newport Beach, Lake Forrest
Coastal OC: Newport Beach, San Clemente, Dana Point, Seal Beach, Laguna Beach, Huntington Beach

These lists are not clear cut, but this is my best attempt so far. For example, Costa Mesa is on the unofficial Northern/Southern border (CA-55), so can be either in Northern or in Southern OC. I put 6 coastal cities, because dropping the smallest one is hard -- Seal Beach and Laguna Beach are about the same size. 

We can play with list compositions later. It will be easy to change them later.

**Comment by thanasibakis** [comment]
Our solution is in the pull request!
