### ISSUE TITLE
Images disappeared

### ISSUE THREAD

**Issue by vnminin** [damonbayer/uci_covid19_dashboard#17]
Images from "OC Maps" and from "About" pages have disappeared after the OC Cities pull request got merged.

**Comment by thanasibakis** [comment]
Oh gosh I'm claiming blame for this one. Thought everything in docs/ is auto-generated, didn't see the assets/ folder. Is anything else in docs/ not generated when I run the build?

**Comment by thanasibakis** [comment]
This new commit brought back the maps but not the about images. Both show up when served locally on my machine. Any ideas?

**Comment by thanasibakis** [comment]
Update: the images appear when using viewing from Damon's GitHub Pages URL, but not from the stat.uci.edu one. I don't think I have enough access to debug that one!
