### ISSUE TITLE
More county sets

### ISSUE THREAD

**Issue by vnminin** [damonbayer/uci_covid19_dashboard#7]
Adding 3-5 additional pages with different sets of 5 counties shown: e.g., a set with 5 SoCal counties, a set of 5 NorCal counties, and a couple of So/Nor county mixes different from we have now.

These would shown up in the drop down menu of under "County Trends"

**Comment by rlongjohn** [comment]
PR: https://github.com/damonbayer/uci_covid19_dashboard/pull/8
